#!/bin/bash

# PM2 Management Commands

echo "PM2 Management Commands:"
echo ""
echo "Start all processes:"
echo "  pm2 start ecosystem.config.js"
echo ""
echo "Stop all processes:"
echo "  pm2 stop all"
echo ""
echo "Restart all processes:"
echo "  pm2 restart all"
echo ""
echo "View logs:"
echo "  pm2 logs"
echo "  pm2 logs semantic-daemon"
echo "  pm2 logs eth-extractor"
echo "  pm2 logs balance-monitor"
echo ""
echo "View status:"
echo "  pm2 list"
echo "  pm2 status"
echo ""
echo "Monitor resources:"
echo "  pm2 monit"
echo ""
echo "Save current process list:"
echo "  pm2 save"
echo ""
echo "Setup startup script:"
echo "  pm2 startup"
echo ""
echo "Delete all processes:"
echo "  pm2 delete all"
